config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :notifications, only: [:destroy]
    member do
      get :followings
      get :followers
      get :likes
      get :feeds
      get :notifications
    end
    collection do
      get :search
    end
  end
  
  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/notification.rb
class Notification < ApplicationRecord

  ACTION_VALUES = ["like", "follow", "comment"]
  validates :action,  presence: true, inclusion: {in:ACTION_VALUES}
  validates :checked, inclusion: {in: [true,false]}
  
  belongs_to :visitor, class_name: 'User'
  belongs_to :visited, class_name: 'User'
  belongs_to :post, optional: true
  belongs_to :comment, optional: true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :correct_user
  
  def destroy
    @notification.destroy
    flash[:success] = '通知を削除しました。'
    redirect_back(fallback_location: root_path)
  end
  
  def correct_user
    @notification = current_user.reverses_of_notification.find_by(id: params[:id])
    unless @notification
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
    
    def unchecked_notifications
        @notifications = current_user.reverses_of_notification.where(checked: false)
    end
end

app/views/notifications/_actions.html.erb
<% case notification.action
  when "follow" %>
    <ul class="list-unstyled mt-4">
      <li class="media d-flex justify-content-between align-items-center">
        <%= image_tag notification.visitor.image.url, alt: "icon", class: "n_icon rounded-circle mr-md-4 mr-1" %>
        <div class="media-body mr-2">
          <%= link_to notification.visitor.name, user_path(notification.visitor) %><span>からフォローされました。</span>
        </div>
        <div class="mr-5">
          <%= time_ago_in_words(notification.created_at) %><span>前</span>
        </div>
        <%= link_to user_notification_path(current_user, notification), method: :delete do %>
          <i class="fas fa-trash-alt fa-lg" aria-hidden="true"></i>
        <% end %>
      </li>
    </ul>
  <% when "like" %>
    <ul class="list-unstyled mt-4">
      <li class="media d-flex justify-content-between align-items-center">
        <%= image_tag notification.post.image.url, alt: "post_image", class: "n_img mr-md-4 mr-1" %>
        <div class="media-body mr-2">
          <%= link_to notification.visitor.name, user_path(notification.visitor) %><span>からいいねがつきました。</span>
          <div class="d-flex">
            <%= link_to '投稿を表示', post_path(notification.post) %>
          </div>
        </div>
        <div class="mr-md-5">
          <%= time_ago_in_words(notification.created_at) %><span>前</span>
        </div>
        <%= link_to user_notification_path(current_user, notification), method: :delete do %>
            <i class="fas fa-trash-alt fa-lg" aria-hidden="true"></i>
        <% end %>
      </li>
    </ul>
  <% when "comment" %>
    <ul class="list-unstyled mt-4">
      <li class="media d-flex justify-content-between align-items-center">
        <%= image_tag notification.post.image.url, alt: "post_image", class: "n_img mr-md-4 mr-1" %>
        <div class="media-body mr-2">
          <%= link_to notification.visitor.name, user_path(notification.visitor) %><span>からコメントがきました。</span>
          <div class="d-flex">
            <%= link_to '投稿を表示', post_path(notification.post) %>
            <p class="ml-2 text-secondary"><%= notification.comment.content %></p>
          </div>
        </div>
        <div class="mr-md-5">
          <%= time_ago_in_words(notification.created_at) %><span>前</span>
        </div>
        <%= link_to user_notification_path(current_user, notification), method: :delete do %>
            <i class="fas fa-trash-alt fa-lg" aria-hidden="true"></i>
        <% end %>
      </li>
    </ul>
<% end %>