config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :notifications, only: [:destroy]
    member do
      get :followings
      get :followers
      get :likes
      get :feeds
      get :notifications
    end
    collection do
      get :search
    end
  end
  
  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
    before_save { self.email.downcase! }
    validates :name, presence: true, length: { maximum: 30 }
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    
    mount_uploader :image, ImageUploader
    
    has_many :posts
    has_many :relationships
    has_many :followings, through: :relationships, source: :follow
    has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
    has_many :followers, through: :reverses_of_relationship, source: :user
    has_many :favorites, dependent: :destroy
    has_many :likes, through: :favorites, source: :post
    has_many :comments, dependent: :destroy
    has_many :notifications, foreign_key:"visitor_id", dependent: :destroy
    has_many :reverses_of_notification, class_name: "Notification", foreign_key:"visited_id", dependent: :destroy
    
    def follow(other_user)
        unless self == other_user
          self.relationships.find_or_create_by(follow_id: other_user.id)
        end
    end
    
    def unfollow(other_user)
        relationship = self.relationships.find_by(follow_id: other_user.id)
        relationship.destroy if relationship
    end
    
    def following?(other_user)
        self.followings.include?(other_user)
    end
    
    def feed_posts
      Post.where(user_id: self.following_ids + [self.id])
    end
    
    def favorite(post)
      self.favorites.find_or_create_by(post_id: post.id)
    end
    
    def unfavorite(post)
      favorite = self.favorites.find_by(post_id: post.id)
      favorite.destroy if favorite
    end
    
    def favorite?(post)
      self.likes.include?(post)
    end
    
    def notify_follow(other_user)
        self.notifications.find_or_create_by(
          visited_id: other_user.id,
          action:"follow"
          )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [
    :show, :edit, :update, :followings, :followers, :notifications
  ]
  before_action :correct_user, only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.order(id: :desc)
    counts(@user)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    
    if @user.save
      flash[:success] = '新規アカウントを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = '入力内容に誤りがあります。'
      render :new
    end
  end

  def edit
  end

  def update
    if params[:user][:password].blank?
      params[:user].delete("password")
    end
    if @user.update(user_params)
      flash[:success] = 'ユーザ情報を更新しました。'
      redirect_to @user
    else
      flash.now[:danger] = '入力内容に誤りがあります。'
      render :edit
    end
  end
  
  def followings
    @user = User.find(params[:id])
    @followings = @user.followings
    counts(@user)
  end
  
  def followers
    @user = User.find(params[:id])
    @followers = @user.followers
    counts(@user)
  end
  
  def likes
    @user = User.find(params[:id])
    @favorites = @user.likes
    counts(@user)
  end
  
  def feeds
    @post = current_user.posts.build
    @posts = current_user.feed_posts.order(id: :desc)
  end
  
  def notifications
    @notifications = current_user.reverses_of_notification.order(id: :desc)
    @notifications.where(checked: false).each do |notification|
      notification.update_attributes(checked: true)
    end
  end
  
  def search
    @users = User.where('name LIKE ?', "%#{params[:name]}%").order(id: :desc)
  end
  
  private
  
  def correct_user
      @user = User.find_by(id: params[:id])
    unless @user == current_user
      redirect_to root_url
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :image, :remove_image)
  end
end

app/views/users/_users.html.erb
<div class="row mt-5">
    <div class=" col-5 d-flex align-items-center">
      <%= image_tag user.image.url, alt: "icon", class: "big_icon rounded-circle" %>
    </div>
    <aside class="col-6">
      <h2><%= user.name %></h2>
      <div class="d-flex justify-content-end mt-5">
        <% if current_user == user %>
          <%= link_to edit_user_path(user) do %>
            <i class="fa fa-user-cog fa-2x"></i>
          <% end %>
        <% end %>
        <%= render 'relationships/follow_button', user: user %>
      </div>
    </aside>
    <ul class="user_list list-unstyled mt-4 mb-5">
      <li>
        <p>投稿</p>
        <div class="badge">
          <%= @count_posts %>
        </div>
      </li>
      <li>
        <p>フォロー</p>
        <div class="badge">
          <%= link_to followings_user_path(user) do %>
            <%= @count_followings %>
          <% end %>
        </div>
      </li>
      <li>
        <p>フォロワー</p>
        <div class="badge">
          <%= link_to followers_user_path(user) do %>
            <%= @count_followers %>
          <% end %>
        </div>
      </li>
    </ul>
</div>

app/views/users/edit.html.erb
<div class="text-center mb-4">
  <div class="head_img_new">
    <%= image_tag @user.image.url, alt: "icon", class: "user_icon rounded-circle mr-2" %>
    <h3>ユーザ情報の編集</h3>
  </div>
</div>

<div class="row">
  <div class="col-md-6 offset-md-3">

    <%= form_with(model: @user, local: true) do |f| %>
        <%= render 'layouts/error_messages', model: f.object %>
        
        <div class="form-group ml-1">
            <%= f.label :image, 'プロフィール画像' %>
            <%= f.file_field :image, id: 'user_image', class: 'form-control-file' %>
            
            <%= f.check_box :remove_image %>
            <%= f.label :remove_image, 'プロフィール画像を削除' %>
        </div>
    
        <div class="form-group mt-md-3">
          <%= f.label :name, 'ユーザ名' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :email, 'メールアドレス' %>
          <%= f.email_field :email, class: 'form-control' %>
        </div>
  
        <div class="form-group">
          <%= f.label :password, '新しいパスワード※変更しない場合は空欄' %>
          <%= f.password_field :password, class: 'form-control' %>
        </div>
        
        <div class="form-group">
          <%= f.label :password_confirmation, '新しいパスワード（確認）' %>
          <%= f.password_field :password_confirmation, class: 'form-control' %>
        </div>
        
        <div class="text-center">
         <%= f.submit '更新', class: 'btn btn-submit rounded-pill' %>
        </div>
    <% end %>
  </div>
</div>

app/views/users/feeds.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'posts/new', post: @post %>
  </aside>
  
  <div class="col-md-5 offset-md-1">
    <ul class="nav nav-tabs justify-content-center mt-4 mb-5">
      <li class="nav-item"><a href="/" class="nav-link <%= 'active' if current_page?(root_path) %>"><i class="fas fa-hashtag" aria-hidden="true"></i>新着</a></li>
      <li class="nav-item"><a href="<%= feeds_user_path(current_user) %>" class="nav-link <%= 'active' if current_page?(feeds_user_path(current_user)) %>"><i class="fas fa-user-friends"></i>フォロー</a></li>
    </ul>
    
    <% if @posts.any? %>
      <ul class="list-unstyled">
        <% @posts.each do |post| %>
          <li class="media mb-5">
            <%= image_tag post.user.image.url, alt: "icon", class: "post_icon rounded-circle" %>
            <div class="media-body">
              <div>
                <h5 class="ml-2"><%= link_to post.user.name, user_path(post.user) %></h5>
              </div>
              <div class="text-right">
                <%= time_ago_in_words(post.created_at) %><span>前</span>
              </div>
              <div class="text-center">
                <%= image_tag post.image.url, alt: "image", class: "img-fluid mb-1" %>
              </div>
              <div class="post_foot">
                <div>
                  <%= link_to 'もっと表示', post_path(post) %>
                </div>
                <div>
                  <%= render 'favorites/likes_button', post: post %>
                </div>
                
              </div>  
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render 'users', user: @user %>
  </div>
  <div class="col-md-6">
    <ul class="nav nav-tabs nav-justified mt-sm-5 mb-5">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="far fa-images fa-lg" aria-hidden="true"></i></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart fa-lg" aria-hidden="true"></i></a></li>
    </ul>
    <div class="card mt-5">
      <div class="card-header">
        <h5 class="card-title d-flex align-items-center justify-content-center">フォロワー</h5>
      </div>
      <div class="card-body">
        <% if @followers.any? %>
          <ul class="list-unstyled">
            <% @followers.each do |follower| %>
              <li class="name_list mb-3">
                <div>
                  <%= image_tag follower.image.url, alt: "icon", class: "user_icon rounded-circle mr-2" %>
                  <%= link_to follower.name, user_path(follower) %>
                </div>
                <div>
                  <%= render 'relationships/follow_button', user: follower %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/followings.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render 'users', user: @user %>
  </div>
  <div class="col-md-6">
    <ul class="nav nav-tabs nav-justified mt-sm-5 mb-5">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="far fa-images fa-lg" aria-hidden="true"></i></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart fa-lg" aria-hidden="true"></i></a></li>
    </ul>
    <div class="card mt-5">
      <div class="card-header">
        <h5 class="card-title d-flex align-items-center justify-content-center">フォロー</h5>
      </div>
      <div class="card-body">
        <% if @followings.any? %>
          <ul class="list-unstyled">
            <% @followings.each do |following| %>
              <li class="name_list mb-3">
                <div>
                  <%= image_tag following.image.url, alt: "icon", class: "user_icon rounded-circle mr-2" %>
                  <%= link_to following.name, user_path(following) %>
                </div>
                <div>
                  <%= render 'relationships/follow_button', user: following %>
                </div>
              </li>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/likes.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render 'users', user: @user %>
  </div>
  <div class="col-md-6">
    <ul class="nav nav-tabs nav-justified mt-sm-5 mb-5">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="far fa-images fa-lg" aria-hidden="true"></i></a></li>
      <li class="nav-item"><a href="<%= likes_user_path(@user) %>" class="nav-link <%= 'active' if current_page?(likes_user_path(@user)) %>"><i class="fas fa-heart fa-lg" aria-hidden="true"></i></a></li>
    </ul>
     <% if @favorites.any? %>
      <div class="row">
        <% @favorites.each do |favorite| %>
          <div class="col-4">
            <div class="thumbnail mb-3">
              <%= link_to post_path(favorite) do %>
                <%= image_tag favorite.image.url, alt: "image", class: "img-fluid" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<div class="row mt-3">
  
  <aside class="col-md-5 text-center mt-md-auto mb-md-auto">
        <p>アカウントをお持ちの方</p>
        <%= link_to "ログインする", login_path, class: "btn btn-white" %>
  </aside>
    
  <div class="col-md-6">
    <div class="card mt-4">
      <div class="card-body">
        
        <h3 class="card-title text-center">新規アカウント登録</h3>
        
        <%= form_with(model: @user, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          <div class="card-text form-group">
            <%= f.label :name, 'ユーザ名' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
    
          <div class="card-text form-group">
            <%= f.label :email, 'メールアドレス' %>
            <%= f.email_field :email, class: 'form-control' %>
          </div>
    
          <div class="card-text form-group">
            <%= f.label :password, 'パスワード' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
    
          <div class="card-text form-group">
            <%= f.label :password_confirmation, 'パスワード（確認）' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>
          
          <div class="card-link text-center">
          <%= f.submit '登録', class: 'btn btn-submit rounded-pill' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/notifications.html.erb
<div class="text-center mt-5 mb-4">
    <h3>通知</h3>
</div>
<div class="row">
  <div class="col-md-8 offset-md-2">
    <% if @notifications.any? %>
      <% @notifications.each do |notification| %>
        <%= render 'notifications/actions', notification: notification %>
      <% end %>
    <% else %>
      <p class="text-center mt-auto mb-auto">通知はまだありません。</p>
    <% end %>
  </div>
    
</div>

app/views/users/search.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <ul class="nav nav-tabs mt-5 mb-4 justify-content-center">
      <li class="nav-item"><a href="<%= search_posts_path %>" class="nav-link <%= 'active' if current_page?(search_posts_path) %>"><i class="far fa-images" aria-hidden="true"></i>投稿</a></li>
      <li class="nav-item"><a href="<%= search_users_path %>" class="nav-link <%= 'active' if current_page?(search_users_path) %>"><i class="fas fa-user-friends"></i>アカウント</a></li>
    </ul>
    
    <div class="mt-5 mb-5 d-flex justify-content-center">
      <%= form_with url: search_users_path, method: :get, local: true do |f| %>
          <%= f.text_field :name, placeholder: "だれを探す？", class: "form-control-inline" %>
          <%= f.submit "検索", class: "btn btn-submit rounded-pill" %>
      <% end %>
    </div>

    <% if @users.any? %>
      <ul class="list-unstyled">
        <% @users.each do |user| %>
          <li class="name_list mb-3">
            <div>
              <%= image_tag user.image.url, alt: "icon", class: "user_icon rounded-circle mr-2" %>
              <%= link_to user.name, user_path(user) %>
            </div>
            <div>
              <%= render 'relationships/follow_button', user: user %>
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center mt-auto mb-auto">ユーザが見つかりませんでした。</p>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <div class="col-md-5">
    <%= render 'users', user: @user %>
  </div>
  <div class="col-md-6">
    <ul class="nav nav-tabs nav-justified mt-sm-5 mb-5">
      <li class="nav-item"><a href="<%= user_path(@user) %>" class="nav-link <%= 'active' if current_page?(user_path(@user)) %>"><i class="far fa-images fa-lg"></i></a></li>
      <li class="nav-item"><a href="#" class="nav-link"><i class="far fa-heart fa-lg"></i></a></li>
    </ul>
     <% if @posts.any? %>
      <div class="row">
        <% @posts.each do |post| %>
          <div class="col-4">
            <div class="thumbnail mb-3">
              <%= link_to post_path(post) do %>
                <%= image_tag post.image.url, alt: "image", class: "img-fluid" %>
              <% end %>
            </div>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>
</div>