config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'posts#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :new, :create, :edit, :update] do
    resources :notifications, only: [:destroy]
    member do
      get :followings
      get :followers
      get :likes
      get :feeds
      get :notifications
    end
    collection do
      get :search
    end
  end
  
  resources :posts, only: [:index, :show, :create, :edit, :update, :destroy] do
      resources :comments, only: [:create, :destroy]
      collection do
        get :search
      end
  end
  
  resources :relationships, only: [:create, :destroy]
  resources :favorites, only: [:create, :destroy]
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  
  validates :content, length: { maximum: 255 }
  validates :image, presence: true
  
  mount_uploader :image, PostImageUploader
  
  has_many :favorites, dependent: :destroy
  has_many :users, through: :favorites
  has_many :comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
  
  def notify_like(current_user)
    unless self.user == current_user
      current_user.notifications.find_or_create_by(
        post_id: self.id,
        visited_id: self.user.id,
        action: "like"
        )
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_user_logged_in
  before_action :correct_user, only: [:edit, :update, :destroy]
  
  def index
    @post = current_user.posts.build  # form_with 用
    @posts = Post.order(id: :desc)
    counts_of(@post)
  end

  def show
    @post = Post.find(params[:id])
    @comments = @post.comments.all
    @comment = @post.comments.build
    counts_of(@post)
  end

  def create
    @post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = '投稿しました。'
      redirect_to root_url
    else
      @posts = current_user.posts.order(id: :desc)
      flash.now[:danger] = '入力内容に誤りがあります。'
      render :index
    end
  end

  def edit
  end

  def update
     if @post.update(post_params)
      flash[:success] = '投稿内容を更新しました。'
      redirect_to @post
    else 
      flash.now[:danger] = '入力内容に誤りがあります。'
      render :edit
    end
  end

  def destroy
    @post.destroy
    flash[:success] = '投稿を削除しました。'
    redirect_to user_path(current_user)
  end
  
  def search
    @posts = Post.where('content LIKE ?', "%#{params[:content]}%").order(id: :desc)
  end

  private
  
  def post_params
    params.require(:post).permit(:content, :image)
  end
  
  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    unless @post
      redirect_to root_url
    end
  end
end

app/views/posts/_new.html.erb
<div class="card mt-5">
  <div class="card-title d-flex align-items-center justify-content-center mt-2">
    <%= image_tag current_user.image.url, alt: "icon", class: "user_icon rounded-circle mr-2" %>
    <h3>新しい投稿</h3>
  </div>
  <div class="card-body">
    <%= form_with(model: post, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="card-text form-group">
        <%= f.file_field :image, id: :post_image, class: 'form-control-file' %>
      </div>
      <div class="card-text form-group">
        <%= f.text_area :content, class: 'form-control', rows: 4 %>
      </div>
      <div class="card-link text-right">
        <%= f.submit '投稿', class: 'btn btn-submit rounded-pill' %>
      </div>
    <% end %>
  </div>
</div>
      

app/views/posts/_new_posts.html.erb
<div class="card mt-5">
  <div class="card-title d-flex align-items-center justify-content-center mt-2">
    <%= image_tag current_user.image.url, alt: "icon", class: "user_icon rounded-circle mr-2" %>
    <h3>新しい投稿</h3>
  </div>
  <div class="card-body">
    <%= form_with(model: post, local: true) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>
      
      <div class="card-text form-group">
        <%= f.file_field :image, id: :post_image, class: 'form-control-file' %>
      </div>
      <div class="card-text form-group">
        <%= f.text_area :content, class: 'form-control', rows: 4 %>
      </div>
      <div class="card-link text-right">
        <%= f.submit '投稿', class: 'btn btn-submit rounded-pill' %>
      </div>
    <% end %>
  </div>
</div>
      

app/views/posts/edit.html.erb
<div class="row">
  <div class="col-md-10 offset-md-1">
    <div class="d-flex align-items-center justify-content-center mt-md-4 mb-4">
      <%= image_tag @post.user.image.url, alt: "icon", class: "user_icon rounded-circle mr-3" %>
      <h3>投稿の編集</h3>
    </div>
    <div class="row mt-md-5">
      <aside class="col-md-6 text-center">
          <%= image_tag @post.image.url, alt: "post_image", class: "img-fluid" %>
      </aside>
      <div class="col-md-6 mt-3">
        <%= form_with(model: @post, local: true) do |f| %>
          <%= render 'layouts/error_messages', model: f.object %>
          
          <div class="form-group">
            <%= f.text_area :content, class: 'form-control', rows: 4 %>
          </div>
          <div class="text-right">
            <%= f.submit '更新', class: 'btn btn-submit rounded-pill' %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="post_edit mt-5">
      <div>
        <%= link_to '<投稿へ戻る', post_path(@post), class: "btn btn-white rounded-pill" %>
      </div>
      <div>
        <%= link_to '投稿を削除', @post, method: :delete, data: { confirm: 'この投稿に対するコメントも全て削除されます。投稿を削除してよろしいですか？' }, class: "btn btn-delete rounded-pill" %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="row">
  <aside class="col-md-4">
    <%= render 'new', post: @post %>
  </aside>
  
  <div class="col-md-5 offset-md-1">
    <ul class="nav nav-tabs justify-content-center mt-4 mb-5">
      <li class="nav-item"><a href="#" class="nav-link active"><i class="fas fa-hashtag" aria-hidden="true"></i>新着</a></li>
    </ul>
    
    <% if @posts.any? %>
      <ul class="list-unstyled">
        <% @posts.each do |post| %>
          <li class="media mb-5">
            <%= image_tag post.user.image.url, alt: "icon", class: "post_icon rounded-circle" %>
            
            <div class="media-body">
              <div>
                <h5 class="ml-2"><%= link_to post.user.name, user_path(post.user) %></h5>
              </div>
              <div class="text-right">
                <%= time_ago_in_words(post.created_at) %><span>前</span>
              </div>
              <div class="text-center">
                <%= image_tag post.image.url, alt: "image", class: "img-fluid mb-1" %>
              </div>
              <div class="post_foot">
                <div>
                  <%= link_to 'もっと表示', post_path(post) %>
                </div>
                <div>
                  <%= render 'favorites/likes_button', post: post %>
                </div>
                
              </div>  
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
  </div>
</div>

app/views/posts/search.html.erb
<div class="row">
  <div class="col-md-6 offset-md-3">
    <ul class="nav nav-tabs justify-content-center mt-5 mb-4">
      <li class="nav-item"><a href="<%= search_posts_path %>" class="nav-link <%= 'active' if current_page?(search_posts_path) %>"><i class="far fa-images" aria-hidden="true"></i>投稿</a></li>
      <li class="nav-item"><a href="<%= search_users_path %>" class="nav-link <%= 'active' if current_page?(search_users_path) %>"><i class="fas fa-user-friends"></i>アカウント</a></li>
    </ul>
    
    <div class="mt-5 mb-5 d-flex justify-content-center">
      <%= form_with url: search_posts_path, method: :get, local: true do |f| %>
          <%= f.text_field :content, placeholder: "何を探す？", class: "form-control-inline" %>
          <%= f.submit "検索", class: "btn btn-submit rounded-pill" %>
      <% end %>
    </div>
    
    <% if @posts.any? %>
      <ul class="list-unstyled justify-content-center">
        <% @posts.each do |post| %>
          <li class="media mb-5">
            <%= image_tag post.user.image.url, alt: "icon", class: "post_icon rounded-circle" %>
            <div class="media-body">
              <div>
                <h5 class="ml-2"><%= link_to post.user.name, user_path(post.user) %></h5>
              </div>
              <div class="text-right">
                <%= time_ago_in_words(post.created_at) %><span>前</span>
              </div>
              <div class="text-center">
                <%= image_tag post.image.url, alt: "image", class: "img-fluid mb-1" %>
              </div>
              <div class="post_foot">
                <div>
                  <%= link_to 'もっと表示', post_path(post) %>
                </div>
                <div>
                  <%= render 'favorites/likes_button', post: post %>
                </div>
              </div>  
            </div>
          </li>
        <% end %>
      </ul>
    <% else %>
      <p class="text-center mt-auto mb-auto">投稿が見つかりませんでした。</p>
    <% end %>
  </div>
</div>

app/views/posts/show.html.erb
<div class="row">
  <aside class="col-md-6 offset-md-1">
    <div class="card mt-5 mb-3">
      <div class="card-body">
        <div class="d-flex align-items-center">
          <%= image_tag @post.user.image.url, alt: "icon", class: "user_icon rounded-circle mr-1" %>
          <div class="card-text">
            <h3><%= link_to @post.user.name, user_path(@post.user) %></h3>
          </div>
        </div>
        
        <div class="card-text text-right">
          <%= time_ago_in_words(@post.created_at) %><span>前</span>
        </div>
        <%= image_tag @post.image.url, alt: "post_image", class: "card-img" %>
        <div class="d-flex align-items-center justify-content-end mb-1">
          <%= render 'favorites/likes_button', post: @post %>
          <%= @count_favorites %>
        </div>
      </div>
    </div>
  </aside>
  <div class="col-md-5">
    <div class="text-right mt-md-5">
      <% if current_user == @post.user %>
        <%= link_to edit_post_path(@post) do %>
          <i class="fas fa-edit fa-lg mr-2" aria-hidden="true"></i>
        <% end %>
        <%= link_to @post, method: :delete, data: { confirm: 'この投稿に対するコメントも全て削除されます。投稿を削除してよろしいですか？' } do %>
          <i class="fas fa-trash-alt fa-lg" aria-hidden="true"></i>
        <% end %>
      <% end %>
    </div>
    <div class="border-bottom border-secondary">
      <p><%= simple_format(@post.content) %></p>
    </div>
    
    <% if @comments.any? %>
      <ul class="list-unstyled mt-3">
        <% @comments.each do |comment| %>
          <li class="media mb-2">
            <%= image_tag comment.user.image.url, alt: "icon", class: "comment_icon rounded-circle" %>
            <div class="media-body">
              <div class="comment_head">
                <div>
                  <p class="font-weight-bold ml-1"><%= link_to comment.user.name, user_path(comment.user) %></p>
                </div>
                <div>
                  <%= time_ago_in_words(comment.created_at) %><span>前</span>
                </div>
              </div>
              <div class="comment_content">
                <p><%= comment.content %></p>
                <% if current_user == comment.user %>
                  <%= link_to post_comment_path(@post, comment), method: :delete, data: { confirm: 'このコメントを削除しますか？' } do %>
                    <i class="fas fa-trash-alt" aria-hidden="true"></i>
                  <% end %>
								<% end %> 
              </div>
            </div>
          </li>
        <% end %>
      </ul>
    <% end %>
    <div>
      <%= image_tag current_user.image.url, alt: "icon", class: "comment_icon rounded-circle mt-3 mb-2" %>
      
      <%= form_with(model: [@post, @comment], local: true) do |f| %>
      
        <div class="form-group">
          <%= f.text_area :content, placeholder: "コメントを書く", class: 'form-control', rows: 3 %>
        </div>
        <div class="text-right">
          <%= f.submit '投稿', class: 'btn btn-submit rounded-pill' %>
        </div>
      <% end %>
    </div>
  </div>
</div>